spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://vacation-db:5435/vacation
    driver-class-name: org.postgresql.Driver
    username: vacation
    password: vacation
    tomcat:
      validation-query: 'select 1'
      test-on-borrow: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    openInView: false
    show_sql: false
    generate-ddl: false
    hibernate:
     ddl-auto: validate
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  data:
    jpa.repositories.enabled: true

server.port: 8080
eureka.client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery:8761/eureka/
    registry-fetch-interval-seconds: 5